#!/usr/bin/env bash
# Generated by data-adapter.sh
# DO NOT EDIT MANUALLY
# This file contains parsed data from user_credentials_clean.json

# Array of all IPs to process
TARGET_IPS=("34.158.38.112" "35.198.224.31")

# Associative array: IP -> space-separated usernames
# Note: Arrays must be pre-declared in parent script

# Associative array: IP -> grep pattern for logs

# Associative array: IP -> chage command chain

IP_USERS["34.158.38.112"]="root ubuntu"
IP_GREP_PATTERN["34.158.38.112"]="root|ubuntu"
IP_CHAGE_CMD["34.158.38.112"]="chage -l root || true && chage -l ubuntu || true"

IP_USERS["35.198.224.31"]="root ubuntu"
IP_GREP_PATTERN["35.198.224.31"]="root|ubuntu"
IP_CHAGE_CMD["35.198.224.31"]="chage -l root || true && chage -l ubuntu || true"


# Helper function: Get user count for an IP
get_user_count() {
    local ip="$1"
    echo "${IP_USERS[$ip]}" | wc -w | tr -d ' '
}

# Helper function: Check if IP exists
ip_exists() {
    local ip="$1"
    [[ -n "${IP_USERS[$ip]:-}" ]]
}

# Note: Arrays must be declared in parent scope before sourcing this file
# declare -a TARGET_IPS
# declare -A IP_USERS IP_GREP_PATTERN IP_CHAGE_CMD
